/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int solid_blue=0x7f040001;
        public static final int solid_green=0x7f040002;
        public static final int solid_red=0x7f040000;
        public static final int solid_yellow=0x7f040003;
    }
    public static final class drawable {
        public static final int aa=0x7f020000;
        public static final int acase=0x7f020001;
        public static final int account=0x7f020002;
        public static final int blue=0x7f02002c;
        public static final int contact=0x7f020003;
        public static final int dark_salesforce=0x7f020004;
        public static final int enjoy_message=0x7f02002b;
        public static final int green=0x7f02002d;
        public static final int home=0x7f020005;
        public static final int ic_popup_reminder=0x7f020006;
        public static final int icon=0x7f020007;
        public static final int icon2=0x7f020008;
        public static final int icon3=0x7f020009;
        public static final int marker=0x7f02000a;
        public static final int opportunity=0x7f02000b;
        public static final int picture_frame=0x7f02000c;
        public static final int red=0x7f020032;
        public static final int salesforce=0x7f02000d;
        public static final int salesforce_cube=0x7f02000e;
        public static final int sample_0=0x7f02000f;
        public static final int sample_1=0x7f020010;
        public static final int sample_10=0x7f020011;
        public static final int sample_11=0x7f020012;
        public static final int sample_2=0x7f020013;
        public static final int sample_3=0x7f020014;
        public static final int sample_4=0x7f020015;
        public static final int sample_5=0x7f020016;
        public static final int sample_6=0x7f020017;
        public static final int sample_7=0x7f020018;
        public static final int sample_8=0x7f020019;
        public static final int sample_9=0x7f02001a;
        public static final int sample_thumb_0=0x7f02001b;
        public static final int sample_thumb_1=0x7f02001c;
        public static final int sample_thumb_10=0x7f02001d;
        public static final int sample_thumb_11=0x7f02001e;
        public static final int sample_thumb_2=0x7f02001f;
        public static final int sample_thumb_3=0x7f020020;
        public static final int sample_thumb_4=0x7f020021;
        public static final int sample_thumb_5=0x7f020022;
        public static final int sample_thumb_6=0x7f020023;
        public static final int sample_thumb_7=0x7f020024;
        public static final int sample_thumb_8=0x7f020025;
        public static final int sample_thumb_9=0x7f020026;
        public static final int screen_background_black=0x7f02002f;
        public static final int scrollbar_vertical_thumb=0x7f020027;
        public static final int scrollbar_vertical_track=0x7f020028;
        public static final int star_big_on=0x7f020029;
        public static final int todo=0x7f02002a;
        public static final int translucent_background=0x7f020030;
        public static final int transparent_background=0x7f020031;
        public static final int yellow=0x7f02002e;
    }
    public static final class id {
        public static final int a_row_array=0x7f060025;
        public static final int auto_complete_view=0x7f060002;
        public static final int calendar_header=0x7f060004;
        public static final int container=0x7f06001d;
        public static final int dashboard1=0x7f060008;
        public static final int dashboard1_title=0x7f060007;
        public static final int dashboard2=0x7f06000a;
        public static final int dashboard2_title=0x7f060009;
        public static final int dashboard3=0x7f06000c;
        public static final int dashboard3_title=0x7f06000b;
        public static final int dateDisplay=0x7f060006;
        public static final int dummy=0x7f060001;
        public static final int gallery=0x7f060011;
        public static final int gps=0x7f060015;
        public static final int item_label=0x7f06000e;
        public static final int item_value=0x7f06000f;
        public static final int layout=0x7f060003;
        public static final int list_top=0x7f060000;
        public static final int menu_sfdc_login=0x7f060022;
        public static final int mv=0x7f060012;
        public static final int one_of_oneline=0x7f060024;
        public static final int one_of_twoline=0x7f060028;
        public static final int pane=0x7f060019;
        public static final int pann=0x7f060018;
        public static final int pans=0x7f06001b;
        public static final int panw=0x7f06001a;
        public static final int row_list_layout=0x7f06001c;
        public static final int salesforce_cancel=0x7f060021;
        public static final int salesforce_login=0x7f060020;
        public static final int salesforce_user_id=0x7f06001e;
        public static final int salesforce_user_password=0x7f06001f;
        public static final int sat=0x7f060013;
        public static final int switcher=0x7f060010;
        public static final int table_account_list_left=0x7f060026;
        public static final int table_account_list_right=0x7f060027;
        public static final int testing=0x7f06000d;
        public static final int text1=0x7f060023;
        public static final int timePicker=0x7f060005;
        public static final int traffic=0x7f060014;
        public static final int two_of_twoline=0x7f060029;
        public static final int zin=0x7f060016;
        public static final int zout=0x7f060017;
    }
    public static final class layout {
        public static final int autocomplete=0x7f030000;
        public static final int autocomplete2=0x7f030001;
        public static final int calendar=0x7f030002;
        public static final int dashboard_array=0x7f030003;
        public static final int detail_array=0x7f030004;
        public static final int detailinfo_array=0x7f030005;
        public static final int document_viewer=0x7f030006;
        public static final int event_calender=0x7f030007;
        public static final int forwarding_target=0x7f030008;
        public static final int google_map=0x7f030009;
        public static final int linear_layout=0x7f03000a;
        public static final int list_array=0x7f03000b;
        public static final int main=0x7f03000c;
        public static final int notepad_list=0x7f03000d;
        public static final int notes_row=0x7f03000e;
        public static final int one_line_list=0x7f03000f;
        public static final int row_array=0x7f030010;
        public static final int table_layout=0x7f030011;
        public static final int two_line_list=0x7f030012;
    }
    public static final class string {
        public static final int acc_info=0x7f050018;
        public static final int acc_list=0x7f050011;
        public static final int app_name=0x7f050000;
        public static final int case_list=0x7f050013;
        public static final int con_list=0x7f050012;
        public static final int document_viewer=0x7f050010;
        /**  Detail Message 
         */
        public static final int event_info=0x7f050017;
        public static final int event_list=0x7f050016;
        /**  forwarding target 
         */
        public static final int forwarding_target=0x7f050019;
        public static final int intent=0x7f050009;
        public static final int label_salesforce_login=0x7f050005;
        /**  ============================== 
  app/search examples strings  
 ============================== 
         */
        public static final int label_salesforce_user_id=0x7f050003;
        public static final int label_salesforce_user_password=0x7f050004;
        public static final int main_menu=0x7f050001;
        public static final int menu_sfdc_login=0x7f050002;
        public static final int message_on_login_nemu_1=0x7f05000a;
        public static final int message_on_login_nemu_2=0x7f05000b;
        public static final int message_on_login_nemu_3=0x7f05000c;
        public static final int message_on_login_nemu_4=0x7f05000d;
        /**  Main menu 
         */
        public static final int message_on_main_menu=0x7f050007;
        /**  Login Message 
         */
        public static final int message_while_login=0x7f05000e;
        public static final int opp_list=0x7f050014;
        /**  Common 
         */
        public static final int sobject_package_name=0x7f050006;
        /**  List message 
         */
        public static final int sobjectlist_postfix=0x7f05000f;
        public static final int sobjectname=0x7f050008;
        public static final int task_list=0x7f050015;
    }
}
